---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Blog Posts
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/authors/authors
  label: Authors
  create: documents
  match: "**/*.yml"
  new_doc_ext: yml
upload_dir: content/posts/images
public_path: "../images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
